# Generated by Django 5.0.7 on 2024-07-18 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locate', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField(default=60)),
                ('region', models.IntegerField(default=0)),
                ('seats', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('elevation_ft', models.CharField(max_length=200)),
                ('continent', models.CharField(max_length=200)),
                ('iso_country', models.CharField(max_length=200)),
                ('iso_region', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=200)),
                ('gps_code', models.CharField(max_length=200)),
                ('iata_code', models.CharField(max_length=200)),
                ('local_code', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('role', models.IntegerField(choices=[(1, 'Assistant'), (2, 'Pilot'), (3, 'Co-Pilot'), (4, 'Flight Attendant'), (5, 'Ground Staff'), (6, 'Cabin Crew'), (7, 'Check-in Agent'), (8, 'Ground Steward')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_trip', models.CharField(max_length=50)),
                ('departure_date', models.DateField()),
                ('infants', models.SmallIntegerField(default=0)),
                ('children', models.SmallIntegerField(default=0)),
                ('adults', models.SmallIntegerField(default=0)),
                ('arrival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_end', to='sito_gestione_voli.airport')),
                ('departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_start', to='sito_gestione_voli.airport')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('infants', models.SmallIntegerField()),
                ('children', models.SmallIntegerField()),
                ('adults', models.SmallIntegerField()),
                ('round_trip', models.CharField(max_length=50)),
                ('arrival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingHistory_end', to='sito_gestione_voli.airport')),
                ('departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingHistory_start', to='sito_gestione_voli.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('total_passengers', models.IntegerField(default=60)),
                ('Aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sito_gestione_voli.aircraft')),
                ('arrival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_end', to='sito_gestione_voli.airport')),
                ('departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_start', to='sito_gestione_voli.airport')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
            },
        ),
        migrations.CreateModel(
            name='FlightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_passengers', models.IntegerField(default=60)),
                ('departure_date', models.DateField(default=django.utils.timezone.now)),
                ('return_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('Aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sito_gestione_voli.aircraft')),
                ('arrival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flightHistory_end', to='sito_gestione_voli.airport')),
                ('departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flightHistory_start', to='sito_gestione_voli.airport')),
            ],
        ),
        migrations.CreateModel(
            name='RoundTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_trip', models.CharField(max_length=50)),
                ('departure_date', models.DateField()),
                ('infants', models.SmallIntegerField(default=0)),
                ('children', models.SmallIntegerField(default=0)),
                ('adults', models.SmallIntegerField(default=0)),
                ('return_date', models.DateField()),
                ('arrival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RoundTrip_arrival_end', to='sito_gestione_voli.airport')),
                ('departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RoundTrip_start_departure', to='sito_gestione_voli.airport')),
                ('return_arrival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RoundTrip_end_return_arrival', to='sito_gestione_voli.airport')),
                ('return_departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RoundTrip_start_return_departure', to='sito_gestione_voli.airport')),
            ],
        ),
    ]
