# Generated by Django 5.0.7 on 2024-07-18 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
