# Generated by Django 5.0.7 on 2024-07-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0002_booking_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateField(),
        ),
    ]
