# Generated by Django 5.0.7 on 2024-07-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito_gestione_voli', '0004_alter_booking_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
